config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  # Ресурс пользователей
  resources :users

  # Ресурс сессий (только три экшена :new, :create, :destroy)
  resource :session, only: [:new, :create, :destroy]

  # Ресурс вопросов (кроме экшенов :show, :new, :index)
  resources :questions, except: [:show, :new, :index]
  
  # Ресурс тегов
  resources :hashtags, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  REGEXP = /#[[:word:]_]+/

  has_many :hashtags_questions, dependent: :destroy
  has_many :questions, through: :hashtags_questions, dependent: :destroy

  validates :name, uniqueness: true

  def to_param
    name
  end
end

app/models/hashtags_question.rb
class HashtagsQuestion < ApplicationRecord
  belongs_to :hashtag
  belongs_to :question

  validates :hashtag_id, uniqueness: { scope: :question_id }
end 

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true, foreign_key: :author_id
  
  has_many :hashtags_questions, dependent: :destroy
  has_many :hashtags, through: :hashtags_questions, dependent: :destroy

  validates :text, :user, presence: true
  validates :text, length: {maximum: 255}
  
  before_save :scan_hashtags

  private

  def scan_hashtags
    hashtags_questions.clear

    "#{text} #{answer}".scan(Hashtag::REGEXP).uniq.each do |name|
      hashtags << Hashtag.find_or_create_by!(name: name)
    end
  end
  
end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord
  # Шифрование паролей
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new

  has_many :questions
  has_many :authorized_questions, class_name: 'Question', foreign_key: :author_id, dependent: :nullify

  validates :email, presence: true, uniqueness: true, format: {with: /\A.+@.+\..+\z/}
  validates :username, presence: true,  length: {maximum: 40}, format: {with: /\A[a-zA-Z0-9_]+\z/}
  validates :profile_color, length: {maximum: 6}, format: {with: /\A[a-fA-F0-9]+\z/}, on: :update, allow_blank: true
  validates_uniqueness_of :username, :case_sensitive => false
  
  before_validation :downcase_username
  
  attr_accessor :password
  validates_presence_of :password, on: :create
  validates_confirmation_of :password
  before_save :encrypt_password
  before_save :set_profile_color

  def downcase_username
    if username.present?
      self.username = username.downcase
    end
  end
  
  def encrypt_password
    if self.password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(self.password, self.password_salt, ITERATIONS, DIGEST.length, DIGEST)
      )
    end
  end
  
  def set_profile_color
    self.profile_color ||= '#005a55'
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  def self.authenticate(email, password)
    user = find_by(email: email)

    if user.present? && user.password_hash == User.hash_to_string(OpenSSL::PKCS5.pbkdf2_hmac(password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST))
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'Вам сюда низя!'
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    @hashtag = Hashtag.find_by!(name: params[:id])
    @questions = @hashtag.questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if check_captcha(@question) && @question.save
      redirect_to user_path(@question.user), notice: 'Вопрос задан'
    else
      render :edit
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Question was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /questions/1
  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Question was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  # Only allow a trusted parameter "white list" through.
  def question_params
    if current_user.present? &&
      params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end

  def check_captcha(model)
    current_user.present? || verify_recaptcha(model: model)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])

    if user.present?
      session[:user_id] = user.id
      redirect_to root_url, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный мэйл или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url notice: 'Вы разлогинились! Приходите снова!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :load_user, except: [:index, :create, :new]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all
    @hashtags = Hashtag.order(:name)
  end

  def new
    redirect_to root_url, alert: "Вы уже залогинены" if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_url, alert: "Вы уже залогинены" if current_user.present?
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, norice: 'Пользователь успешно зарегистрирован!'
    else
      render 'new'
    end
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), norice: 'Данные обновлены'
    else
      render 'edit'
    end
  end

  def edit
  end

  def show
    @questions = @user.questions.order(created_at: :desc)

    @new_question = @user.questions.build
    
    @questions_count = @questions.count
    @answers_count = @questions.where.not(answer: nil).count
    @unanswered_count = @questions_count - @answers_count
  end
  
  def destroy
    @user.destroy
    redirect_to root_url, notice: 'Ваш профиль удалён'
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :profile_color)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end
  
  def profile_color(user)
    if user.profile_color.present?
      user.profile_color
    else
      return '#005a55'
    end
  end
  
  def author(question)
    if question.author.present?
      link_to question.author.username, user_path(question.author)
    else
      return 'Анонимный пользователь'
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
  
  def sklonenie(number, one, few, many)
    if(number == nil || !number.is_a?(Numeric))
      number = 0
    end

    return many if (number % 100).between?(11, 14)
    return one if (number % 10) == 1
    return few if (number % 10).between?(2, 4)
  
    return many
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def add_hashtag_links(s)
    result =
      s.gsub(Hashtag::REGEXP) do |name|
        link_to name, hashtag_url(name), class: 'hashtag'
      end
    result.html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hashtags/show.html.erb
<div class="container content-wrapper buffer-both">
  <div class="column-1-2">
    <%= render @questions %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>AskMe</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <div class="header">
      <div class="header-logo">
        <h1 class="header-title"><%= link_to "AskMe", root_path %></h1>
      </div>
      <div class="header-nav">
        <%# Если есть текущий юзер (значит он залогинен) %>
        <% if current_user %>
          <%# Даем ссылки на его профиль и на логаут %>
          <%= link_to "@#{current_user.username}", user_path(current_user) %> |
          <%= link_to 'Выйти', session_path, data: {method: :delete} %>
        <% else %>
          <%# Если нету — ссылки на регистрацию и логин %>
          <%= link_to 'Зарегистрироваться', new_user_path, class: 'button button-light button-small' %>
          <%= link_to 'Войти', new_session_path, class: 'button button-light button-small' %>
        <% end %>
    </div>
   </div>

    <div class="content">
      <div class="container">
        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>
    <%= yield %>
      </div>
    </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/questions/_form.html.erb
<%# Форма для создания/правки вопроса %>
<div class="form">
  <%# Форма для объекта @question %>
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
      <%= f.label :answer, 'Ответ', class: 'form-label' %>
      <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

<%# Хелпер капчи %>
<%= recaptcha_tags unless current_user.present? %>
  
    <%# Скрытое поле — айдишник юзера, кому задается вопрос %>
    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label :text, 'Вопрос', class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <%# Простая авторизация - может ли текущий юзер править вопрос? %>
    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label :answer, 'Ответ', class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<%# Это фрагмет (паршал, partial) для вывода вопроса. В нем определена %>
<%# локальная переменная question, в которую при вызове будет передан %>
<%# как в метод ruby объект после ключа (object: @question) %>

<div class="question">
  <div class="question-content">
    <%# Текст вопроса %>
    <div class="question-text text-lead">
      <%= add_hashtag_links(question.text) %>
    </div>

    <%# Текст ответа, если он есть %>
    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= add_hashtag_links(question.answer) %>
      </div>
    <% end %>
    <div class="question-author">
      <%= author(question) %>
    </div>
    <%# Дата создания вопроса (отформатированная) %>
    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <%# Если адресат вопроса — текущий пользователь, он может редактировать вопрос %>
  <%# и отвечать на него %>
  <% if question.user == current_user %>
    <%# Определяем какая будет иконка, если у вопроса нет ответа, то иконка %>
    <%# овтета на письмо, иначе — карандашик %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<%# Страница редактирования вопроса %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<%# Страница редактирования пользователя %>
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Править профиль</h1>

  <div class="column-1-2">
    <%# С помощью специального хелпера form_for мы делаем тег <form ...> %>
    <%# с нужными аттрибутами, после этого в переменной f будет специальный %>
    <%# объект (form builder object), вызывая методы которого мы можем %>
    <%# создавать теги для нужных нам полей формы. %>
    <%= form_for(@user) do |f| %>
      <%# Вывод ошибок валидации пользователя, если есть. Ошибки содержатся %>
      <%# в поле errors модели (в нашем случае @users). %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%# С помощью методов label и text_field у объекта f мы создаем теги %>
      <%# <label ... > и <input type="text" ... > с нужными атрибуами %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <%# Поступаем аналогично для других полей %>
      <div class="form-field">
        <%= f.label 'Ваше имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label 'URL вашей аватарки', class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>
    
      <div class="form-field">
        <%= f.label 'Цвет вашего профиля', class: 'form-label' %>
        <%= f.text_field :profile_color, class: 'form-text-field jscolor' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        <p>Если не хотите менять пароль — оставьте эти поля пустыми!</p>
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      </div>
    <% end %>
    
    <div class="buffer-top">
      <p>Внимание! Профиль удаляется навсегда</p>
      <%= link_to 'Удалить профиль', user_path(@user), class: 'button button-small button-red',
        method: :delete, data: {confirm: 'Вы действительно хотите удалить профиль?'} if current_user == @user %>
    </div>

    <%# Подробнее про помощники для создания форм: %>
    <%# http://guides.rubyonrails.org/form_helpers.html %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium">Наши пользователи</h1>
  </div>
  <% @users.each do |user| %>
    <div class="users-list-item">
      <div class="user-image-div user-image-div-small">
        <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
      </div>
    </div>
  <% end %>
  <div class="buffer-both">
    <h3>Хэштеги</h3>
    <% @hashtags.each do |hashtag| %>
      <% if hashtag.questions.present? %>
        <span>
          <%= link_to hashtag.name, hashtag_url(hashtag), class: 'hashtag' %>
        </span>
      <% end %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background: #<%= profile_color(@user) %>">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>

  <div class="user-ask-button container text-center">
    <%= link_to "Спроси меня", '', class: 'button button-light', id: 'ask-button' %>
  </div>

    <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= sklonenie(@questions_count, 'вопрос', 'вопроса', 'вопросов') %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answers_count %></h1>
      <p><%= sklonenie(@answers_count, 'ответ', 'ответа', 'ответов') %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p><%= sklonenie(@answers_count, 'без ответа', 'без ответа', 'без ответов') %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>

        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= f.label "Ваш вопрос для @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>
          <%= recaptcha_tags size: 'compact' unless current_user.present? %>

        <div class="form-action">
          <%= submit_tag 'Задать вопрос', class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>

  </div>
</div>

<div class="column-3-4">
  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>